web:
  build: .
  dockerfile: Dockerfile
  tty: true
  stdin_open: true
  ports:
    - 3000:3000
  expose:
    - 3000
  volumes:
    - ".:/test-dev"
  environment:
    - RAILS_ENV=development
    - REDIS_URL=redis://@redis:6379/15
    - API_AUTHORIZATION=development
  links:
    - db
    - redis

db:
  image: postgres:10.5
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: testdev
  ports: ["5432:5432"]
  expose: ["5432"]

redis:
  container_name: test-dev-redis
  image: redis:alpine
  ports:
    - "6379:6379"
  expose:
    - "6379"

sidekiq:
  build: .
  command: sidekiq
  tty: true
  stdin_open: true
  volumes:
    - ".:/test-dev"
  environment:
    - RAILS_ENV=development
    - REDIS_URL=redis://@redis:6379/15
    - API_AUTHORIZATION=development
  links:
    - db
    - redis