web:
  build: .
  dockerfile: Dockerfile
  tty: true
  stdin_open: true
  ports:
    - 3000:3000
  expose:
    - 3000
  volumes:
    - ".:/test-dev"
  environment:
    - RAILS_ENV=development
    - API_AUTHORIZATION=development
  links:
    - db

db:
  image: postgres:10.5
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: testdev
  ports: ["5432:5432"]
  expose: ["5432"]